### ISSUE TITLE
Why not static

### ISSUE THREAD

**Issue by Fewald** [jmfeurprier/perf-http-status#1]
May be it's a newbie question, but why not declare these Http11StatusRepository Http10StatusRepository classes as static?
It's seems good to just get the status string without an object creation.

**Comment by jmfeurprier** [comment]
Hi, and thanks a lot for taking the time to ask this question, which is frequently asked (and also applies to the Singleton pattern).

## The short answer:

Static classes are limiting.

## The long answer:

If object creation is a concern for you for performance, do not worry, this is definitely not where a bottleneck will appear in your application (profiling tools are here to help you locate bottlenecks).

If object creation is a concern for you for the ease of use (like, having 1 line of code to retrieve a HTTP status string vs. 2 lines of code), then there are other ways to achieve this (examples of alternatives will follow).

### Why static classes are limiting

In general, static classes defeat the purpose of polymorphism (which is why the HttpStatusRepository interface is here): with concrete classes, you could substitute a Http11StatusRepository object by a Http10StatusRepository, and your application would run the same way (expecting a HttpStatusRepository class/interface):

``` php
class Whatever
{

    private $httpStatusRepository;

    public function __construct(HttpStatusRepository $repository)
    {
        $this->httpStatusRepository = $repository;
    }

    public function notFound()
    {
        return $this->httpStatusRepository->get(404);
    }
}

// Both object will work (almost) the same:
$whatever = new Whatever(new Http10StatusRepository());
$whatever = new Whatever(new Http11StatusRepository());
```

With static calls, once a call is written in your code, your application will not be able to fetch HTTP/1.0 statuses anymore, as there is now a "hard-wiring" (a.k.a. coupling) to a class:

``` php
function whatever()
{
    $status = Http11StatusRepository::get(404); // Bound to HTTP/1.1 implementation

    header($status);
}
```

With static classes, you lose the ease of unit-testing of your code, as you'd have no way of replacing a real production-ready HttpStatusRepository by a testing double (see https://phpunit.de/manual/current/en/test-doubles.html):

``` php
public function testNotFound()
{
    $httpStatusRepositoryMock = $this->getMock('\\perf\\Http\\Status\\HttpStatusRepository');
    // More mocking stuff

    $whatever = new Whatever($httpStatusRepositoryMock);

    $result = $whatever->notFound();

    // Assert stuff
}
```

Static classes and methods makes them accessible from everywhere, which is a open door for spaghetti code (have you ever seen a typical Symfony 1.x application?).

Not the case here but just to highlight it: static classes (and also singletons) can carry a state which can be altered and shared accross an application, which could lead to unexpected behavior.

### Alternatives:
- Keep on instanciating an object prior to retrieve a HTTP status string (not convenient).
- Instanciate it once, somewhere, then access it when needed (not optimal, because maybe sometimes you won't need it)
- Use a dependency-injection container, which will only instanciate the object (once) if needed (see https://symfony.com/doc/current/components/dependency_injection/index.html).

Also, and just for convenience (for quick and not-so-dirty developments), we could add and use a static constructor (which I just added in release 1.0.1):

``` php
$status = Http11StatusRepository::create()->get(404);
```

This approach gives the benefit of accessing the repository statically (even though it's baaad), but without making the class static.

### More references:

Object-oriented terminology -- http://www.giorgiosironi.com/2009/10/object-oriented-terminology.html
Why static classes are evil! -- http://blog.goyello.com/2009/12/17/why-static-classes-are-evil/
Why Singletons are Evil -- http://blogs.msdn.com/b/scottdensmore/archive/2004/05/25/140827.aspx
Named Constructors in PHP -- http://verraes.net/2014/06/named-constructors-in-php/

Hope that answers your (not so newbie) question :)

**Comment by Fewald** [comment]
Thank you for your time and this answer! It's helpful and contains something new for me to learn.
